//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCourseManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeCourse
    {
        public int TraineeCourseId { get; set; }
        public string TraineeCode { get; set; }
        public int TraineeId { get; set; }
        public int CourseId { get; set; }
        public int BatchId { get; set; }
        public string Result { get; set; }
        public int UserDetailsId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Course Course { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
